name: Build & Push Docker Image to ECR(NONPROD_account)

on:
  workflow_call:
    inputs:
      PERIOD:
        description: "Additional tag to select a runner for the job execution"
        required: false
        type: string
        default: "1"
      DEPLOY_NAME:
        description: "Additional tag to select a runner for the job execution"
        required: false
        type: string
      RUNS_ON:
        description: "Additional tag to select a runner for the job execution"
        required: false
        type: string
        default: "self-hosted"

jobs:
  Build_and_Deploy_to_prod:
    runs-on: 
      - ${{ inputs.RUNS_ON }}
    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Test github runner privillege
      run: |
        kubectl rollout restart deploy  ${{ inputs.DEPLOY_NAME }} -n prod-viwell
        sleep "${{ inputs.PERIOD }}m"
        kubectl get pods -n prod-viwell | grep -i ${{ inputs.DEPLOY_NAME }}

        
